# -*- coding: utf-8 -*-
"""VISUALISATIONS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VUwc-41pIY5Hg9ifwewCTT0q-D7pE9vo
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
file_path = '/content/MLTempDataset.csv'
data = pd.read_csv(file_path)

# Convert 'Datetime' to pandas datetime format
data['Datetime'] = pd.to_datetime(data['Datetime'])

# Plot 1: Line plot of room temperature over time
plt.figure(figsize=(12, 5))
plt.plot(data['Datetime'], data['DAYTON_MW'], color='orange')
plt.title('Room Temperature Over Time')
plt.xlabel('Time')
plt.ylabel('Temperature (°C)')
plt.xticks(rotation=45)
plt.show()

# Plot 2: Scatter plot of room temperature
plt.figure(figsize=(12, 5))
sns.scatterplot(x=data['Datetime'], y=data['DAYTON_MW'], color='blue', s=10)
plt.title('Scatter Plot of Room Temperature')
plt.xlabel('Time')
plt.ylabel('Temperature (°C)')
plt.xticks(rotation=45)
plt.show()

# Plot 3: Histogram of room temperature values
plt.figure(figsize=(8, 5))
sns.histplot(data['DAYTON_MW'], bins=30, kde=True, color='purple')
plt.title('Distribution of Room Temperature')
plt.xlabel('Temperature (°C)')
plt.show()

# Plot 4: Box plot to observe temperature distribution
plt.figure(figsize=(6, 5))
sns.boxplot(data=data, y='DAYTON_MW', color='green')
plt.title('Box Plot of Room Temperature')
plt.ylabel('Temperature (°C)')
plt.show()

# Plot 5: Bar plot for sample points (aggregated weekly mean temperatures)
data.set_index('Datetime', inplace=True)
weekly_data = data['DAYTON_MW'].resample('W').mean().reset_index()

plt.figure(figsize=(10, 5))
sns.barplot(x='Datetime', y='DAYTON_MW', data=weekly_data, color='skyblue')
plt.title('Weekly Average Room Temperature')
plt.xlabel('Week')
plt.ylabel('Temperature (°C)')
plt.xticks(rotation=45)
plt.show()